### ISSUE TITLE
bugg sur visualisation de la fiche adhérent

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#1]
Bonjour Patrick, 
En me connectant en tant que pierre albrecht j'ai bien les droits admin. "751859"
En allant sur gestion des adhérents j'ai bien toute la liste des adhérents. par contre 2 bugg: 
1 =>En cliquant sur mon nom, j'ai une erreur  HTTP 500 "Impossible to access an attribute ("title") on a null variable."  donc pas moyen de changer une infos sur ma fiche.
2=> De retour sur gestion des adhérents, en filtrant sur la liste des chamois par exemple, j'ai bien que des chamois, mais sur deux pages car plus de 15 chamois. En sélectionnant la page "2" on se retrouve avec toutes la liste des adhérents, il faut donc à nouveau sélectionner chamois pour avoir la seconde partie de la liste des chamois.

Autre alerte HTTP500, si je souhaite m'inscrire depuis la page d'accueil via les boutons à droite "voir le programme" à la sortie du 25/07 rando adulte et ado => HTTP500 

Dernier bugg, étant connecté sur mon compte lorsque je vais sur "Programme du club" j'ai une proposition de "Disponibilite" pour la sortie du 20/07/21.  en cliquant sur Disponibilité =>  HTTPP 500

Tout cela doit être lier au fait qu'il manque un statut de niveau dans mon cas.

Bon courage pour la suite.

**Comment by pasojucle** [comment]
Bonjour @VTTPierre, j'ai remis le site à jour avec les corrections
