### ISSUE TITLE
Modifier programme perso

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#107]
Connecter sur le compte d'un encadrant, pas possible de modifier le programme perso avec le stylo..  =>  bugg
Revoir largeur de pagination si possible.  Ecole VTT et sera présent sont superposés.

https://user-images.githubusercontent.com/87672341/188730462-19bd7c79-59ab-47fa-9f34-9b38b4afb4f4.mp4

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/188942513-e3b317c1-0c80-4db9-a3b7-0282754996c7.png)
![image](https://user-images.githubusercontent.com/54477272/188942619-58ad4cde-b466-4fbf-9eb8-bb0c1c73e1b7.png)

**Comment by VTTPierre** [comment]
on peut clore ce ticket, après correction du mot disponib`i`lité  (manque un i)  et suppression de l'accent pour le `a`bien été
![disponibilité a été](https://user-images.githubusercontent.com/87672341/188967958-179db9d3-2519-4158-a3bc-d4b967d4fd61.png)
