### ISSUE TITLE
Travail sur base actuelle:Supprimer compte totototo174 sur site existant. et ajouter tuto dans inscription

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#110]
bonjour Patrick,

Peux-tu supprimer les éléments lié au compte TOTOtoto174.
J'ai créé ce dernier sur le site actuel pour avoir des captures d'écran.

![supp_totototo174](https://user-images.githubusercontent.com/87672341/189738553-3397cfcd-df1c-4b98-9572-e74685ced6f4.png)

Pour finir, est-il possible de rendre accessible le tuto. pdf ci-dessous dans l'onglet inscription et ajouter un onglet tutoriel.
Autre point à modifier sur la base actuelle, ne pas créer le compte avant le téléchargement du dossier en fin de création de compte.
Cela évite d'avoir des dossiers dans un état en attente de création.

[tuto_inscription.pdf](https://github.com/pasojucle/vtt_evasion_ludres/files/9551174/tuto_inscription.pdf)

**Comment by VTTPierre** [comment]
ne pas hésiter à m'appeler si besoin de plus d'info.
Bon courage

**Comment by pasojucle** [comment]
Bonjour @VTTPierre et @sylvainVTT. 
Je pourrai très bien mettre le compte en session et enregistrer en base qu'a la fin de l'inscription, mais ça à un gros inconvénient : comme il y a de multiple formulaire, si il y a un problème sur l'un d'eux, on perd toutes la saisie des formulaires précédent, et pour l'utilisateur, c'est agaçant de recommencer.
De plus,  le système n'est pas prévu comme ça, et ça va prendre du temps de développement et de test.
Pour les dossiers en attente de création qui restent en suspend, on peut prévoir un système pour les purger au besoins, ça remet moins de choses en cause.
Dites-mois

**Comment by pasojucle** [comment]
@VTTPierre @sylvain je ne pense pas que l'on soit utile de se déconnecter entre l'inscription au club, et l'inscription à une sortie

**Comment by VTTPierre** [comment]
Bonsoir Patrick.
Je ne sais pas, en tout cas nous avions un blocage d'une personne qui cherchait à s'inscrire à la séance sans avoir validé son dossier, c'est pour cela que j'ai monté le tuto dans ce sens. avec déconnexion et reconnexion.
On pourra toujours modifier et reprendre le tuto lors du déploiement du nouveau site.

@pasojucle Pour la suppression des données en base, tu es surement plus callé que moi.

**Comment by sylvainvtt** [comment]
Slu Patrick,Si. En fait il faut que le mail de création de compte ne parte qu'au moment du téléchargement du dossier et ne pas connecter le compte. Cela obligera les gens à aller voir le mail et "à apprendre"" à se connecter. Faut pas tout leur faire 😉😉😉MerciSylvainvtt 😁Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 13/09/2022  18:48  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Travail sur base actuelle:Supprimer compte totototo174 sur site existant. et ajouter tuto dans inscription (Issue #110) 

@VTTPierre @Sylvain je ne pense pas que l'on soit utile de se déconnecter entre l'inscription au club, et l'inscription à une sortie

**Comment by VTTPierre** [comment]
En accord avec le Patron,J'ai répondu directement sur le ticket githubenvoyé : 13 septembre 2022 à 19:43de : sylvainvtt ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>cc : VTTPierre ***@***.***>, Mention ***@***.***>objet : Re: [pasojucle/vtt_evasion_ludres] Travail sur base actuelle:Supprimer compte totototo174 sur site existant. et ajouter tuto dans inscription (Issue #110) Slu Patrick,Si. En fait il faut que le mail de création de compte ne parte qu'au moment du téléchargement du dossier et ne pas connecter le compte. Cela obligera les gens à aller voir le mail et "à apprendre"" à se connecter. Faut pas tout leur faire 😉😉😉MerciSylvainvtt 😁Envoyé depuis mon appareil Galaxy -------- Message d'origine --------De : pasojucle ***@***.***> Date : 13/09/2022 18:48 (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Travail sur base actuelle:Supprimer compte totototo174 sur site existant. et ajouter tuto dans inscription (Issue #110)   @VTTPierre @Sylvain je ne pense pas que l'on soit utile de se déconnecter entre l'inscription au club, et l'inscription à une sortie    —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
