### ISSUE TITLE
Pas possible de faire attestation CE sur site de prod. en cours

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#114]
Il n'est pas possible de faire une attestation CE sur l'année 2022 ! On ne peut le faire que sur les nouveaux ou les réinscrits

**Comment by pasojucle** [comment]
![attestation_ce](https://user-images.githubusercontent.com/54477272/191343813-47c8b9cf-5c1b-445a-92d5-72dcbabbc45e.png)
