### ISSUE TITLE
re-inscription dossier ancien adhérent, bugg étape 4

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#12]
Dans le dossier de re-inscription il y a un bugg à l'étape 4

"formulaire santé"

@Pierre

étape 3 OK
![inscription-ancien_etape_3](https://user-images.githubusercontent.com/87672341/127911767-9e3107db-e538-4e7c-bffa-4b3e58dec21e.png)

étape 4 NOK
![inscription-ancien_etape_4](https://user-images.githubusercontent.com/87672341/127911769-d18826c0-bb21-428c-9fe6-fb93e3d4bf63.png)

**Comment by VTTPierre** [comment]
L'étape téléchargement renvoi la même erreur.

@Pierre

![inscription-ancien_etape_7](https://user-images.githubusercontent.com/87672341/127912462-4a311888-b027-4cb9-a217-4a5e8ffcc500.png)

**Comment by pasojucle** [comment]
Bonjour @VTTPierre. Ils manquait des infos à l'import du fichier des adhérents. C'est modifié.

ça m'a fait penser que si l'inscription était validée, elle ne devrait plus modifiable. J'ai modifié en conséquence.  Tu peux faire le test en validant ta licence dans l'administration, et repasser sur le site pour faire l'inscription à nouveau. Dis moi si ça vous convient ?

![Capture d’écran du 2021-08-07 17-06-46](https://user-images.githubusercontent.com/54477272/128604912-10051c44-8e7a-4c9c-8fc3-4c8ae9a6c647.png)

**Comment by VTTPierre** [comment]
Tout semble ok au niveau de la ré-inscription ou modification d'inscription.
Ajout de la photo d'identité, 

Pierre
