### ISSUE TITLE
filtre gestion adhérents

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#120]
Pouvoir lister tous les adhérents quelle que soit la saison.
Laisser la saison en cours par défaut mais donner la possibilité de soit tout afficher, soit faire une sélection multiple sur 2 saisons.

https://user-images.githubusercontent.com/87672341/193861579-50f3f21f-dc0d-4271-b48c-82f262ba2272.mp4

**Comment by pasojucle** [comment]
Bonjour @VTTPierre 
![image](https://user-images.githubusercontent.com/54477272/193887854-e6bc9938-1f52-4921-b2ae-a62f73fe0968.png)
Si tu cliques sur la croix en haut à gauche, la saison est supprimer du filtre et tu obtient la liste de tous les adhérents

**Comment by VTTPierre** [comment]
OK bien noté 
J'ai pas noté la subtilité de la petite croix 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : mardi 04 octobre 2022 19:38À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] filtre gestion adhérents (Issue #120)

Bonjour @VTTPierre



Si tu cliques sur la croix en haut à gauche, la saison est supprimer du filtre et tu obtient la liste de tous les adhérents
