### ISSUE TITLE
Désinscrire

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#122]
Ajouter un texte "Se désinscrire"   à la place de la croix ou à coté
Plus modifier l'info-bulle annuler par "Se désinscrire"

![désincrire](https://user-images.githubusercontent.com/87672341/193870526-4ca74ba2-91e9-4391-bec2-9e4c2c39673f.png)

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/194121218-48ee681d-b469-4b22-8cbd-351aaedcfb16.png)
