### ISSUE TITLE
Onglet Boutique (pour site de test)

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#124]
Vérifier, en ouvrant la boutique par un adhérent, qu'il n'y ai pas de commande en cours de création dans le panier, sinon l'afficher pour continuer la saisie. Afficher également ses commandes qu'il a commandées mais sur lesquelles il ne pourra plus rien rajouter.

**Comment by pasojucle** [comment]
@sylvainvtt A la connexion de son compte, si il y  a une commande en cours, le papier s'affiche à coté du nom.

![image](https://user-images.githubusercontent.com/54477272/195154402-65052a8d-8261-4983-aa25-b02ff6cb7cb9.png)

Si on vas dans la boutique et que l'on ajoute un produit, il s'ajoute au panier cours.
On peut voir aussi les commande en cours et l'historique des commande dans mon compte/mes commandes

![image](https://user-images.githubusercontent.com/54477272/195155352-d92b44f9-958a-4a02-8bd0-535699ca1fda.png)

**Comment by sylvainvtt** [comment]
Slt Patrick,C ce qui existait déjà ou tu viens de le faire ?Quand un panier est en cours, pouvons-nous afficher un pop-up qui averti d'un panier non-validé et ce, à chaque connexion ? Bonne journéeSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 11/10/2022  19:07  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Onglet Boutique (pour site de test) (Issue #124) 

@sylvainvtt A la connexion de son compte, si il y  a une commande en cours, le papier s'affiche à coté du nom.



Si on vas dans la boutique et que l'on ajoute un produit, il s'ajoute au panier cours.

On peut voir aussi les commande en cours et l'historique des commande dans mon compte/mes commandes

**Comment by sylvainvtt** [comment]
Slt Patrick,En fait quand on supprime les articles du panier, l'icône reste affichée. Il faut supprimer l'icône quand le panier est vide.SylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 11/10/2022  19:07  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Onglet Boutique (pour site de test) (Issue #124) 

@sylvainvtt A la connexion de son compte, si il y  a une commande en cours, le papier s'affiche à coté du nom.



Si on vas dans la boutique et que l'on ajoute un produit, il s'ajoute au panier cours.

On peut voir aussi les commande en cours et l'historique des commande dans mon compte/mes commandes
