### ISSUE TITLE
Attestation adulte accompagnateur

### ISSUE THREAD

**Issue by pasojucle** [pasojucle/vtt_evasion_ludres#125]
[ANNEXE 5 - ATTESTATION ADULTE ACCOMPAGNATEUR.PDF.pdf](https://github.com/pasojucle/vtt_evasion_ludres/files/9813906/ANNEXE.5.-.ATTESTATION.ADULTE.ACCOMPAGNATEUR.PDF.pdf)

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/196521143-df099f13-1200-47ec-8c5e-940d48e574eb.png)
![image](https://user-images.githubusercontent.com/54477272/196521409-374994c5-6dc2-4416-ad34-3cc33cad6cb1.png)

**Comment by VTTPierre** [comment]
Patrick, est-il possible d'ajouter une partie dans le texte comme ci-dessous:
Peut-être intégrer le logo du club ainsi que celui de la FF vélo.

A voir avec sylvain

Cette fonction donne accès à une certaine partie d’informations utiles à l’organisation de nos séances d’école cyclo.
{{ nom_prenom }}s’engage à ne pas utiliser ou divulguer ces informations en dehors de toute activité liée à cette organisation.

**Comment by VTTPierre** [comment]
petite remarque, l'attestation Adulte Accompagnateur ne doit être dispo que pour la rubrique Adulte Accompagnateur

Les Moniteurs, Initiateurs, ou Animateurs sont par défaut des adultes accompagnateurs

![adulte_accomp_only](https://user-images.githubusercontent.com/87672341/198560232-7e004df2-3d03-4b36-b3a8-0dc04261dd10.png)
