### ISSUE TITLE
Logo croix rouge

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#126]
Patrick,

Serait-il possible d'intégrer un petit logo croix rouge à côté de la maison verte ou rouge  pour les adhérents ayant un champ Pathologie, Allergie ou Intolérance de renseigné dans la fiche sanitaire. Cela permettrait à chaque encadrant d'avoir un visuel rapide avant la séance pour voir s'il y a une info santé. 

Exemple de présentation pour le cas de Hugo: 

![croix-rouge](https://user-images.githubusercontent.com/87672341/198568011-2d5404ae-677c-4d91-9353-195bcd4fd92c.png)

Cela concernerait l'ensemble des champs ci-dessous, dès lors que l'un d'eux soit coché.
Exemple de la fiche de MARIN Matéo

![pathologie](https://user-images.githubusercontent.com/87672341/198568429-96ea0fbb-60b6-4d70-aeba-c2e23a78cc72.png)

**Comment by VTTPierre** [comment]
Lorsque la pathologie est Autre, le logo ne s'affiche croix rouge ne s'affiche pas . 
Exemple Brasseur Gaël

**Comment by pasojucle** [comment]
@VTTPierre @sylvainVtt
Comme vous ne vouliez pas forcement avoir la croix rouge pour des pathologie qui n’empêchent pas la pratique du vtt comme une allergie alimentaire, vous pouvez par le menu paramétrage/pathologie, paramètrer si vous souhaitez afficher ou non la croix pour chaque pathologie
