### ISSUE TITLE
Gestion/Inscriptions

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#129]
Le tri de droite : renouvellement ne fonctionne pas. Il faut y mettre toutes les ré-inscriptions, avant validation. Et dans le tri "Inscription", il ne faut y mettre que les nouveaux inscrits, avant validation.
![image](https://user-images.githubusercontent.com/88937051/199215924-6c7c6295-585b-4b3a-86a4-de4e0ba0492d.png)

**Comment by pasojucle** [comment]
@sylvainvtt Est-ce que ça te parait plus cohérent ?
[export_renouvellements.csv](https://github.com/pasojucle/vtt_evasion_ludres/files/9909488/export_renouvellements.csv)
[export_nouvelle inscription.csv](https://github.com/pasojucle/vtt_evasion_ludres/files/9909489/export_nouvelle.inscription.csv)

**Comment by sylvainvtt** [comment]
Slt Patrick,Il y a juste Brasseur Julien qui était en séance d'essai sur 2022 et qui vient seulement de s'inscrire sur 2023. En fait, à partir du moment où ils ont un identifiant qui n'est pas un numéro de licence, ils doivent être en nouvelle inscription.Bon mardimanche 😉SylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 01/11/2022  12:52  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Gestion/Inscriptions (Issue #129) 

@sylvainvtt Est-ce que ça te parait plus cohérent ?

export_renouvellements.csv

export_nouvelle inscription.csv
