### ISSUE TITLE
Programme des sorties

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#133]
Bonjour Patick,

Ajouter un Item : Animation club  (cela peut être une séance photo, un atelier Carto ou mécanique, Reconnaissance de parcours...)

Modifier l'Item Rando adultes et ados (sans encadrement)

![programmes des sorties](https://user-images.githubusercontent.com/87672341/200889382-4560bb72-630f-4ec5-9de0-b91cd5c508e1.png)

**Comment by pasojucle** [comment]
@VTTPierre @SyvainVtt
Vous pouvez ajouter ou modifier un type de sortie via le menu paramètrage/types de rando.
J'ai fait la modif et ajouté les ateliers. Il faudra vérifier si vous vouller des indemnités pour ce type.

![image](https://user-images.githubusercontent.com/54477272/200905574-c47666bf-5630-45d5-a0ff-11454176d72e.png)

Je pense que ce ticket est lié à [SONDAGE lié à une activité et une population #134](https://github.com/pasojucle/vtt_evasion_ludres/issues/134).

Dans ce cas il ne faut pas utiliser les sondages, mais créer une rando dans laquelle on puisse sélectionner le type ou niveau de personne qui peut y participer, et éventuellement déclencher la pop'up pour ces personnes

Qu'en pensez-vous ?

**Comment by VTTPierre** [comment]
Bonsoir Patrick,J'essaie de voir comment faire pour adresser cette animation aux adultes du samedi  (animateur, accompagnant, certains parent hors encadrement, initiateur, moniteur)En fait le seul point commun c'est qu'ils sont majeurs et donc +18 ans. (donc créer une rando ou animation avec âge minimum.En passant par le module de gestion du type de rando je ne vois pas comment intégrer la population ciblée.Pour moi le seul choix reste le sondage adressé à chaque personne. ou l'inscription à l'animation.Dans l'idée il faudrait pouvoir limiter le nombre d'inscriptions à une sortie.Je vais créer la séance animation et on verra comment on va gérer.envoyé : 9 novembre 2022 à 19:16de : pasojucle ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>cc : VTTPierre ***@***.***>, Mention ***@***.***>objet : Re: [pasojucle/vtt_evasion_ludres] Programme des sorties (Issue ***@***.*** @SyvainVtt Vous pouvez ajouter ou modifier un type de sortie via le menu paramètrage/types de rando. J'ai fait la modif et ajouté les ateliers. Il faudra vérifier si vous vouller des indemnités pour ce type.Je pense que ce ticket est lié à SONDAGE lié à une activité et une population #134.Dans ce cas il ne faut pas utiliser les sondages, mais créer une rando dans laquelle on puisse sélectionner le type ou niveau de personne qui peut y participer, et éventuellement déclencher la pop'up pour ces personnesQu'en pensez-vous ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by pasojucle** [comment]
@VTTPierre @ sylvaintVtt Effectivement il y avait un bug que je viens de corriger. J'ai crée le type de rando "Animation club".

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/203847526-636d52b4-0229-472c-902c-52a5fd35b8d5.png)

**Comment by VTTPierre** [comment]
Bonsoir PatrickÇa semble pas mal tout cela, on va tester cela prochainement.Merci pour ton travail.Bonne soiréeenvoyé : 24 novembre 2022 à 19:25de : pasojucle ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>cc : VTTPierre ***@***.***>, Mention ***@***.***>objet : Re: [pasojucle/vtt_evasion_ludres] Programme des sorties (Issue #133) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
