### ISSUE TITLE
accès admin light ciblé

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#140]
Bonjour Patrick, 

Nous souhaiterions pouvoir limiter l'accès à la base coté admin.

En fait nous avons des initiateurs qui ne sont pas ou plus présents aux séances du samedi et donc leur retirer les droits d'admin light.
Nous avions pensé à trois options:

1. Donner les droits que si la personne est inscrite aux séances du programme, et ne les ouvrir que de 13h à 18h30 pour ce qui est du samedi ou bien de 8h00 à 12h30 pour le dimanche matin et pour je ne sais quelle heure sur des séances en dehors de ces deux cas. cela peut être problématique en cas de changement d'horaire sur une sortie particulière.
2. Peut-être permettre l'accès admin light uniquement lorsque la personne est inscrite sur une séance et fermer l'accès le soir à minuit dès que la date est passée.
3. Sinon permettre aux Admin +++ (Sylvain et Pierre) de pouvoir cocher ou décocher une option d'admin sur la fiche de l'encadrant.

Tout ceci est de la programmation informatique et là je ne maitrise pas de tout.

A ta dispo pour en parler et voir ce qui serait le plus simple, et le plus efficace. Le but étant de limiter l'accès aux donnée personnelles et sensibles tout en nous permettant de fonctionner normalement.
En attendant j'ai mis le statut "adulte hors encadrement" à 2 personnes afin qu'elles n'aient plus d'accès admin light.
Mais cela va forcément fausser les exports et suivi des niveaux des personnes.

Bonne journée.

**Comment by pasojucle** [comment]
Bonjour @VTTPierre et  @sylvainVtt. Le plus simple est de vous laisser tout les deux gérer les droits depuis la fiches de chaque encadrant. En plus on peut lorsque qu'un encadrant est inscrit à une sortie, le rediriger directement sur les groupes de la sortie à laquelle il est inscrit, sur toute la journée, sinon lui mettre un message qu'il n'a pas de sortie en cours. Qu'en pensez-vous ?

**Comment by VTTPierre** [comment]
Bonjour @pasojucle et @sylvainvtt,
Si on a moyen de cocher les adultes ayant droit ou pas sur la fiche de l'adhérent indépendamment de son statut (anim, init, moniteur) je pense que c'est le plus simple. 
Aux admin +++ (Sylvain et Pierre) de définir qui est autorisé ou pas.

@sylvain ton avis!

**Comment by sylvainvtt** [comment]
Slt,Oui ce serait déjà ça. Mais n'avoir accès aux détails des jeunes que si l'on est inscrit à une sortie et uniquement le temps de cette journée serait top. Idem pour les boutons verrouiller et exporter. En fait comme c'est déjà maintenant (voir les inscrits et pouvoir se positionner sur un groupe) mais pas d'accès aux fiches des adhérents, jeunes ou adultes).Bonne journéeSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : VTTPierre ***@***.***> Date : 29/11/2022  10:57  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] accès admin light ciblé (Issue #140) 

Bonjour @pasojucle et @sylvainvtt,

Si on a moyen de cocher les adultes ayant droit ou pas sur la fiche de l'adhérent indépendamment de son statut (anim, init, moniteur) je pense que c'est le plus simple.

Aux admin +++ (Sylvain et Pierre) de définir qui est autorisé ou pas.

@Sylvain ton avis!

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/204617849-bafdb77b-9804-4b2c-a11c-e1661414488e.png)

**Comment by sylvainvtt** [comment]
Par contre laisser la fonction open bar aux Adim +++
Si possible pour pouvoir corriger si besoin ou imprévu. 
 
Envoyé depuis l'application Mail Orange
----------------De : sylvain.kohler ***@***.***>Envoyé : mardi 29 novembre 2022 11:34À : pasojucle/vtt_evasion_ludres ***@***.***>; VTT Com. ALBRECHT Pierre ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] accès admin light ciblé (Issue #140)Slt,Oui ce serait déjà ça. Mais n'avoir accès aux détails des jeunes que si l'on est inscrit à une sortie et uniquement le temps de cette journée serait top. Idem pour les boutons verrouiller et exporter. En fait comme c'est déjà maintenant (voir les inscrits et pouvoir se positionner sur un groupe) mais pas d'accès aux fiches des adhérents, jeunes ou adultes).Bonne journéeSylvainEnvoyé depuis mon appareil Galaxy-------- Message d'origine --------De : VTTPierre ***@***.***> Date : 29/11/2022  10:57  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] accès admin light ciblé (Issue #140) 

Bonjour @pasojucle et @sylvainvtt,

Si on a moyen de cocher les adultes ayant droit ou pas sur la fiche de l'adhérent indépendamment de son statut (anim, init, moniteur) je pense que c'est le plus simple.

Aux admin +++ (Sylvain et Pierre) de définir qui est autorisé ou pas.

@Sylvain ton avis!

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/204871046-189308bc-b3fb-4e16-9e41-c3b00392ff69.png)


![Capture d’écran du 2022-11-30 18-46-13](https://user-images.githubusercontent.com/54477272/204870795-2d5df7fd-c6a8-4da4-9b25-3f6d741267ae.png)

**Comment by pasojucle** [comment]
**Corrections pour l'admin des encadrants**
Les encadrants ont accès à la liste des sorties
![image](https://user-images.githubusercontent.com/54477272/207678266-6d1ae55e-08ed-4489-9225-1849047d304c.png)

Le lien à la fiches des adhérents, le bouton pour pointer les présences, pour clôturer et exporter les groupes sont désactivés pour les encadrants. Seul le menu pour changer de groupe reste accessible.<br>
Le jour de la sortie, si ils sont inscrits, tout redevient actif.<br>
![image](https://user-images.githubusercontent.com/54477272/207680302-3895ef2c-9763-46cc-b0c3-30030f0db739.png)
