### ISSUE TITLE
OUPS,  export selection

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#141]
Bonjour Patrick,

Je rencontre des Oups lors des exports.
J'ai beau attendre et revenir dessus par la suite c'est pareil

https://user-images.githubusercontent.com/87672341/204493128-5fef10f2-03ca-46e6-915a-1b6d23170f9a.mp4

**Comment by pasojucle** [comment]
Bonjour @VTTPierre . C'est corrigé
