### ISSUE TITLE
doublon d'inscription à la séance

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#142]
Patrick,

Nous avons eu un doublon d'inscription à la séance de ce jour.  03-12-22
Pourras tu regarder ce point?
![doublon inscription séance](https://user-images.githubusercontent.com/87672341/205454972-981ee4b4-edab-44e1-ba5b-4cba69587471.png)

**Comment by sylvainvtt** [comment]
Patrick,
Pour info, j'ai rajouté ce participant vendredi à la demande de sa maman parce qu'elle avait oublié. J'ai fait "Ajouter un participant" parce que, étant vendredi, il n'était plus possible de l'inscrire par son identifiant.
