### ISSUE TITLE
ordre alphabétique pour les encadrants

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#143]
Patrick

Peux-tu faire un affichage par ordre Alphabétique pour la liste des encadrants, ce sera plus simple à chercher.

![ordre Alpha](https://user-images.githubusercontent.com/87672341/205455090-6fab444f-1052-4bb6-82d7-ad5c9bf81afa.png)

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/206543379-d68cb0a0-daf9-432d-8ef5-855d4c58a49a.png)
