### ISSUE TITLE
Inscription avortée

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#144]
Pourrait-on afficher un message disant que le dossier d'inscription ou ou ré-inscription n'est pas finalisé (en cours de création) à chaque log de l'adhérent concerné ?
Merci

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/206894900-848016b4-daab-4fec-ad4b-3c9ce27874c6.png)

**Comment by sylvainvtt** [comment]
Slt Patrick,Merci pour les têtes en l'air 🙄Bon dimancheSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 11/12/2022  09:57  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Author ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Inscription avortée (Issue #144)
