### ISSUE TITLE
Inscription des adultes aux séances VTT

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#145]
Envoyer un mail de confirmation aux adultes qui s'inscrivent à une sortie ou autre du programme (comme pour les jeunes).

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/206900708-1e275c06-222d-4edb-9bf5-e173de4cbf07.png)

**Comment by pasojucle** [comment]
La confirmation s'adapte au choix de l'encadrant.<br>Avez vous  une meilleur formulation lorsque que la personne se rend disponible ?<br>
![image](https://user-images.githubusercontent.com/54477272/207417836-8290f61a-fe85-410b-8a4d-14ae0095a28d.png)
![image](https://user-images.githubusercontent.com/54477272/207418377-aabc39cb-7e94-4135-b223-683c38125cf7.png)
![image](https://user-images.githubusercontent.com/54477272/207418539-94ec0139-c874-4cde-81a8-80f462549733.png)

**Comment by sylvainvtt** [comment]
Slt Patrick,Dans le 2e cas je mettrais :Votre disponibilité si besoin ....Comme ça on est raccord avec les propositions.SylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 13/12/2022  19:47  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Author ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Inscription des adultes aux séances VTT (Issue #145) 
La confirmation s'adapte au choix de l'encadrant.Avez vous  une meilleur formulation lorsque que la personne se rend disponible ?
