### ISSUE TITLE
Inscription à une sortie du programme sans être réinscrit au club

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#146]
Il faudrait bloquer l'accès à l'inscription aux séances du programme (école VTT ou adulte) si on n'est pas réinscrit pour la nouvelle saison. Mettre un champ pour saisir une date à partir de laquelle on ne peut plus accéder sans être réinscrit. Il faut que l'inscription au club pour la nouvelle saison soit validée dans l'onglet des inscriptions.

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/207112995-cc16916b-9173-494a-840b-08ef12edc7c8.png)

**Comment by sylvainvtt** [comment]
Slt Patrick,Oui c bon. Juste corriger : "transmettre" 😉Merci et bonne soiréeSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 12/12/2022  18:29  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Author ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Inscription à une sortie du programme sans être réinscrit au club (Issue #146)

**Comment by sylvainvtt** [comment]
Tu peux aussi enlever la virgule après "club" et mettre seulement 2023.MerciEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 12/12/2022  18:29  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Author ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Inscription à une sortie du programme sans être réinscrit au club (Issue #146)
