### ISSUE TITLE
Module adhérents

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#148]
Il faudrait pouvoir identifier les membres du bureau et du comité : 
Président
Vice-Président
Secrétaire
Secrétaire adjoint
Trésorier
Trésorier adjoint
Membre du comité
Par défaut, les 6 membres du bureau sont au comité.
Dans le module Adhérent, il faudra rajouter "Membres du bureau et comité" dans le menu de tri de recherche.

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/208737619-3649bbf6-9e2b-47b3-a87f-6c12a2453b70.png)<br>
![image](https://user-images.githubusercontent.com/54477272/208737743-8ad2fb07-1082-477e-b3de-3b9e2c57e6c0.png)<br>
![image](https://user-images.githubusercontent.com/54477272/208738165-fb908157-03c6-4894-b370-2857a65d3173.png)<br>
![image](https://user-images.githubusercontent.com/54477272/208740087-2ec7afeb-8ce6-4c5d-bf84-b6e1e44776be.png)

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/208740604-73915a72-880b-403f-bbda-045c222481ae.png)
<br>
![image](https://user-images.githubusercontent.com/54477272/208740715-a6e66b03-2d46-49a8-9e4b-2b4430611d67.png)

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/208746062-51c7773b-9a75-4b0c-a596-9e39ba3c6a31.png)

**Comment by sylvainvtt** [comment]
Salut Patrick,On vient d'avoir confirmation que nous ne pouvons conserver les données médicales de nos adhérents à moins d'avoir une sécurité digne de Fort Knox 😁De ce fait, il faut effacer de la base de données purement et simplement toutes ces données :Numéro Secu, mutuelle et numéro de mutuelle, groupe sanguin, pathologies, nom et adresse du médecin traitant, vaccin antitétanique.Il faudra donc "squizzer" ce passage sur le bulletin d'inscription. On va s'occuper de noircir ces données sur les bulletins d'inscription en notre possession 🙄Merci et bonne soiréeSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 22/12/2022  17:23  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Author ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Module adhérents (Issue #148) 
Closed #148 as completed.
