### ISSUE TITLE
Avertissement de modif sur le bulletin de réinscription

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#153]
Serait-ce possible de faire apparaître sur le bulletin d'adhésion (réinscription) si des modifications ont eu lieu par rapport à celui de l'année précédente ? C'est à dire les faire apparaître en gras par exemple ? Ceci concerne les champs remplit par l'adhérent. Pas urgent, pour la rentrée prochaine.

**Comment by pasojucle** [comment]
**Les modifications sont en gras**
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/29806948-fc83-40d7-91e1-48dc06915d00)
![inscription_vtt_evasion_ludres-1](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/99b73189-32f4-4659-b854-de1f30a3e1f7)
