### ISSUE TITLE
changer de groupe  NOK

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#154]
Patrick,

j'ai bien réussi à ajouter des groupes ( Ateliers _1-2-3) par contre je ne peux pas ventiler les jeunes dans les divers groupes.
Seul moyen, positionner de façon "définitive" dans la fiche adhérent le niveau. Chose que nous ne souhaitons pas car ce n'est que pour une ou deux séances.

Petite vidéo qui montre la création des groupes, mais ceux-ci ne sont plus dispo lors de la sélection changer de groupe

https://user-images.githubusercontent.com/87672341/211142949-9897ffd4-8bda-4c9a-bd32-d775210588e0.mp4

**Comment by pasojucle** [comment]
Possibilité d'ajouter, modifier et supprimer un groupe à une sortie.<br>
La suppression ne peut se faire que si il n'y a plus de participant dans le groupe.
Les boutons "voir l'encadrement" et  "Ajouter un participant" ont été déplacés dans le menu.<br>
![image](https://user-images.githubusercontent.com/54477272/211888068-3062bd0d-cfa1-4245-af93-78243fb68185.png)<br>
![image](https://user-images.githubusercontent.com/54477272/211888218-314a3f90-5fbc-429e-ba40-19d528645fb3.png)<br>
![image](https://user-images.githubusercontent.com/54477272/211888403-e1ee00ae-e782-490c-9e62-17848a57a779.png)
