### ISSUE TITLE
ajout d'une base documentaire école vtt

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#155]
Patrick

Serait-il possible d'ajouter une page Documentation dans la partie Ecole VTT
L'idée est de pouvoir y déposer des documents ( Pdf ou Jpeg) pour les jeunes de l'école dans le cadre de la formation pour les critérium et autre épreuves. 

Les documents pouvant être dans la bibliothèque ou dans le corps du message comme le Tuto inscription.
Vois pour le plus simple.

![documents](https://user-images.githubusercontent.com/87672341/211262331-ccedc586-eda1-4128-a330-fda6159c4c7e.png)

**Comment by VTTPierre** [comment]
Bonjour Patrick 
Oui l'idée et de pouvoir déposer des documents pdf ou jpeg dans l'onglet "École VTT" sous une rubrique "Documents" 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : jeudi 12 janvier 2023 19:00À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] ajout d'une base documentaire école vtt (Issue #155)

Bonjour @VTTPierre. Si je fait une liste de fichiers pdf ou jpeg avec un lien qui permet aux que les jeunes  d'afficher ou télécharger,  liste que tu pourrais administrer par l'admin, ça te convient ?

**Comment by VTTPierre** [comment]
Patrick. 
Je n'ai pas accès au site de test. 
Vidage de cache, ctrl F5.... 
Bref ça ne marche pas. Je n'arrive pas à avoir les mêmes infos que toi. 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : jeudi 12 janvier 2023 19:00À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] ajout d'une base documentaire école vtt (Issue #155)

Bonjour @VTTPierre. Si je fait une liste de fichiers pdf ou jpeg avec un lien qui permet aux que les jeunes  d'afficher ou télécharger,  liste que tu pourrais administrer par l'admin, ça te convient ?

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/212546305-42776c27-2368-4834-b468-4e4f6b076557.png)
<br>
![image](https://user-images.githubusercontent.com/54477272/212546225-3e85e22b-8a18-4a4d-a23b-0b5910480c10.png)
<br>
![image](https://user-images.githubusercontent.com/54477272/212546142-fd3a4ca6-a3b6-44a7-9aaa-386415d692bb.png)
