### ISSUE TITLE
export sortie avant date de l'évènement  (non urgent)

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#158]
Patrick,

Serait-il possible de pouvoir générer un export pour Sylvain et moi (Admin ++) afin de pouvoir extraite les personnes inscrites à une sortie ou activité fédérale avant que la date ne soit atteinte.
En gros il nous faut fournir la liste des inscrits avec n° licence, date de naissance, nom prénom.. généralement une semaine avant l'évènement. 
Je ne sais pas si tu moyen de faire un ajout d'export (Export Admin) ou simplement lever le blocage de date sur "Exporter la séance" pour Sylvain et moi (surement le plus simple).

![exporter seance](https://user-images.githubusercontent.com/87672341/213999741-08367802-d5ba-4a11-bd8e-83332570399d.png)

**Comment by pasojucle** [comment]
@VTTPierre , on peut désormais exporter la liste à tous moment. J'ai ajouter la date de naissance. Il faudra me dire s'il faut ajouter d'autre infos dans l'export

**Comment by VTTPierre** [comment]
Merci Patrick 
Bon dimanche 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : samedi 28 janvier 2023 18:40À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] export sortie avant date de l'évènement  (non urgent) (Issue #158)

@VTTPierre , on peut désormais exporter la liste à tous moment. J'ai ajouter la date de naissance. Il faudra me dire s'il faut ajouter d'autre infos dans l'export
