### ISSUE TITLE
Ajout participants

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#159]
Patrick,

Peux tu voir pour nous donner la possibilité d'ajouter un participant ayant encore le statut 3 séances en cours.

**Comment by pasojucle** [comment]
![Capture d’écran du 2023-01-28 13-28-50](https://user-images.githubusercontent.com/54477272/215266464-ccf4b22f-167f-411e-95ba-346937b5a4e2.png)
