### ISSUE TITLE
Sondage (acces info sondage)

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#160]
Patrick

Aurais tu moyen de permettre l'accès infos sondage pour les participants  (exemple séance CDER à pont à mousson)  nous sommes aveugle et pas moyen pour les adhérents de retourner sur le sondage pour voir les infos.

**Comment by pasojucle** [comment]
bonjour @VTTPierre. Si j'ai bien compris, voudrais que les inscrits à la sortie puissent retrouver, depuis leurs espace personnel,  les infos contenues dans le sondage liées à cette sortie ?<br>
![image](https://user-images.githubusercontent.com/54477272/215183450-d3bc24b2-0c51-42ba-9cd8-e1e32b2355b4.png)

**Comment by VTTPierre** [comment]
Oui tout à fait 
Tu as tout compris. 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : vendredi 27 janvier 2023 20:47À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] Sondage (acces info sondage) (Issue #160)

bonjour @VTTPierre. Si j'ai bien compris, voudrais que les inscrits à la sortie puissent retrouver, depuis leurs espace personnel,  les infos contenues dans le sondage liées à cette sortie ?

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/215261268-13c26c28-6ac2-46c0-8480-e79be2d4faf4.png)
<br>
![image](https://user-images.githubusercontent.com/54477272/215261304-9692f9eb-9715-438d-af56-9b6109adf1e2.png)

**Comment by VTTPierre** [comment]
Parfait 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : samedi 28 janvier 2023 11:19À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] Sondage (acces info sondage) (Issue #160)
