### ISSUE TITLE
inscription séances (3 séances)

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#161]
Bonjour Patrick,

>Nous avons un souci pour que Tatiana qui est en 3 séances d'essai puisse s'inscrire.
Lorsqu'elle se connecte sur sont compte et qu'elle tente de s'inscrire elle à le message suivant.

![3 essais tatiana](https://user-images.githubusercontent.com/87672341/218260371-7c155cf2-0bc7-4b53-a035-b66116b04823.png)

Ne pas tenir compte de la date ni du type de séance c'est juste que je n'ai pas voulu modifier le paramètre de la sortie école de ce jour.

Elle en est à sa troisième séance d'essai mais son compteur est resté bloqué à 0 car nous n'arrivons pas à l'inscrire sur les séances.

![tatiana](https://user-images.githubusercontent.com/87672341/218260452-af71f839-8841-45b7-8d49-9789df4a3dba.png)

Ceci est un cas mais je suppose que si un nouvel adhérent souhaite bénéficier des 3 séances d'essai on risque de se retrouver dans la même situation.
La solution serait de valider son dossier mais nous n'avons son dossier définitif.

Bon courage pour démêler tout ceci.

**Comment by pasojucle** [comment]
Modification de la règle pour autoriser tout adhérent qui possède une licence en attente de validation en période d'essai ou non
