### ISSUE TITLE
Inscription adultes dimanche

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#162]
Afficher pour tous les adhérents uniquement les nom et prénom de ceux qui se sont inscrits pour la sortie.

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/218298360-5aa77306-2352-477d-9ba0-6c087c73b3b7.png)<br>
![image](https://user-images.githubusercontent.com/54477272/218298579-54884062-2dca-4c9c-b4e5-53122a4b8b19.png)

**Comment by sylvainvtt** [comment]
Bon ça va, tu vas pouvoir t'installer ds le canapé devant le petit écran maintenant 😅. Bonne soiréeSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 21/03/2023  20:50  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Author ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Inscription adultes dimanche (Issue #162) 
Closed #162 as completed.
