### ISSUE TITLE
impossible de s'inscrire au critérium du 19 mars

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#163]
Bonjour Patrick,

Nous avons le critérium de Dongermain le 19 mars prochain et j'ai créé une sortie fédérale mais je n'arrive pas à m'inscrire.
J'ai modifié un peu le format avec 3 groupes.

J'ai notre ami ""OUPS"" qui me dit bonjour.

en pj les vidéos

https://user-images.githubusercontent.com/87672341/220985924-30776b0c-57de-4cd9-90ef-f9d19c3fa756.mp4

https://user-images.githubusercontent.com/87672341/220985950-a4181ac7-af91-471c-a01e-85bd4602eb49.mp4

**Comment by pasojucle** [comment]
Bonjour @VTTPierre. C'est corrigé

**Comment by VTTPierre** [comment]
Merci Patrick. 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : jeudi 23 février 2023 22:12À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] impossible de s'inscrire au critérium du 19 mars (Issue #163)

Bonjour @VTTPierre. C'est corrigé
