### ISSUE TITLE
Participation du dimanche matin

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#166]
Il serait bien de pouvoir s'inscrire pour le dimanche matin en choisissant un groupe prédéfini : Groupe 1 (avions de chasse), Groupe 2 (randonneurs avertis), Groupe 3 (débutants. remise en forme).
Faire incrémenter le compteur (reste bloqué à 0)

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/226701267-8f964fa1-bce2-4e4d-b161-395718119e30.png)
<br>
![image](https://user-images.githubusercontent.com/54477272/226702325-848cbbfe-5e31-4400-911f-d7ddfe4bb758.png)
