### ISSUE TITLE
Affichage dans programme

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#167]
Quand une activité au programme est finie, il serait bien de faire apparaître le nombre de participants à l'activité dans l'historique. Ca permettrait de montrer au visiteurs lambda la dynamique du club (merci Pierre).

A l'affichage de la page "programme" ne pourrait-on pas afficher "Tous" en commençant par la page en cours ? De ce fait, les visiteurs verraient qu'il y a un historique (voir copie écran) et la participation :
![image](https://user-images.githubusercontent.com/88937051/223962294-f7223299-6e51-4e0c-b61f-16e27dc9223d.png)

Merci Patrick

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/227734558-05039cb2-0c98-4491-959d-b5f297339cd9.png)
