### ISSUE TITLE
Autorisation image (photos)

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#171]
Dans la liste des adhérents inscrits à une sortie (ou toute autre activité), à côté du nom, afficher un pictogramme (rouge barré pour non et vert non barré pour oui) d'un appareil photo permettant de visualiser facilement si l'autorisation à l'image est acceptée ou non.

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/227761740-af2a8055-6716-4992-8c6c-652a771634c9.png)
