### ISSUE TITLE
filtre sur adhérents actifs de la saison  "NON URGENT"

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#172]
Bonjour Patrick,

En voulant sélectionner des adhérents sur une sortie, (ne limiter qu'a certains adhérents) je me rends compte que TOUS les adhérents connus de la base sont accessibles. (2021-2022-2023...)
Aurais tu moyen de ne laisser l'accès qu'aux adhérents de la saison.
Dans l'exemple, en pj, Richard, Gabin et Mathias ne sont plus adhérents au club cette saison.

Autre point lié au sujet, serait-il possible d'importer de façon systématique la liste des encadrants (moniteur et initiateurs) dès que l'on crée une sortie fédérale ?  ou alors pouvoir importer un fichier txt ou csv. 

![liste adhérents](https://user-images.githubusercontent.com/87672341/227865286-cbf5490c-d9d1-488b-859e-54e1670e0180.png)

**Comment by pasojucle** [comment]
Ajout d'un filtre sur les adhérents actifs et d'un bouton pour ajouter les encadrants<br>
![image](https://user-images.githubusercontent.com/54477272/230150453-7fabeaee-cc5e-41c2-bede-f6ab94321061.png)
