### ISSUE TITLE
Afficher SES choix de sondages

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#173]
Patrick

Serait-il possible de faire apparaitre les choix validés par chaque adhérent sur son compte lorsqu'il se connecte sur la rubrique, mon programme perso.

En gros pouvoir afficher les renseignements tel que saisis lors de la première connexion et validation, mais ne ps donner la possibilité de modifier les choix.

![sondage_post inscription](https://user-images.githubusercontent.com/87672341/228516973-6c3c27b5-d3a0-43e9-b213-29d340230f1b.png)

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/229341824-7f595493-bc0c-434d-b3ea-a9d255350883.png)
