### ISSUE TITLE
état de disponibilité des encadrants non actif sur sortie fédérale

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#174]
Bonjour Patrick,

Sur les sortie fédérales nous n'avons pas la vision de l'encadrement.
pour exemple l'activité CJCR à pont a mousson le 06 mai
La sortie étant créé avec un sondage et limitée à un nombre prédéfini de personnes, je pense que nous ne pourrons pas avoir les vues classiques d'une sortie du samedi.

ci dessous le pavé dans la page du programme est s'inscrire et non disponibilité
![crer_1](https://user-images.githubusercontent.com/87672341/233766639-02025d72-60ff-4694-92f6-75f9d8ff06a9.png)

Là on peut choisir le groupe dans lequel on souhaite s'inscrire
![crer_2](https://user-images.githubusercontent.com/87672341/233766649-bfcb76c0-52b6-4a68-bdcc-d3cb983805e6.png)

Et là le champ passe à vide lorsque la personne s'est inscrite.
![crer_3](https://user-images.githubusercontent.com/87672341/233766653-0ff606ed-bce4-43e5-9022-deaf78be6198.png)

C'est surement le fonctionnement normal, si tu pouvais faire en sorte que sur ce type de sortie on puisse avoir "inscrit" au lieu de vide pour ceux qui se sont inscrit.

On va voir l'avis de M. Le Président pour ce ticket.

**Comment by pasojucle** [comment]
Ajout d'un paramètre pour la nécessité d'un encadrement pour un type de sortie<br>
![image](https://user-images.githubusercontent.com/54477272/233853348-d29d4297-cb3b-4e91-b9be-0184ad88d6b0.png)<br>
![image](https://user-images.githubusercontent.com/54477272/233853469-437a6a90-b060-4dfc-a23b-140d07fc846c.png)<br>
![image](https://user-images.githubusercontent.com/54477272/233853514-58b1ff5c-5887-4c61-96b6-2dd31e62c24a.png)<br>
![image](https://user-images.githubusercontent.com/54477272/233854172-e80e974f-b384-4b86-b100-e94561504848.png)
