### ISSUE TITLE
Ajouter un encart Bonnes affaires ou Bourse d'échange, Seconde vie...

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#175]
Bonjour Patrick et Sylvain, 

Pourrions nous créer une rubrique occasion , vente matos, bonnes affaires, seconde vie  (titre à déterminer)
Pour préparer la rentrée de septembre 2023, mettre en place une rubrique de vente ou revente de matériel.
L'idée est de permettre aux adhérents ayant des objets en lien exclusif avec le VTT de pouvoir les revendre à d'autres membres du club. Je pense surtout aux fringues qui sont souvent trop court après un an chez les jeunes et également les vélos qui deviennent trop petit à force de pédaler.
Nous avons souvent des demandes de débutants qui cherchent un VTT adapté.
Reste à déterminer le formalise de cette rubrique et voir comment on gère.
Par mail exclusivement avec une photo max par article ou bien seulement le descriptif et les personnes se mettent en contact par la suite. 
Je veux bien me charger de mettre en ligne si besoin.
Pourrions nous dans ce cas créer une adresse mail en lien avec ce sujet, un alias d'adresse afin d'avoir un suivi et un historique dans la base.
Bref encore un nouveau chantier qui je pense mérite réflexion.

A discuter ensemble.

**Comment by pasojucle** [comment]
Bonjour @VTTPierre @sylvainvtt,
On peut imaginer le système suivant

- côté acheteur, on ajoute une rubrique, "mes annonces", comprenant  un formulaire pour déposer l'annonce avec son descriptif, une photo et son prix, avec possibilité de la modifier ou la supprimer.
- à la création d'une nouvelle annonce, elle est envoyée à un modérateur qui doit valider pour la mettre en ligne.
- les annonces sont visibles sur le site depuis une nouvelle rubrique accessible à tous ou uniquement aux personnes identifiées (à définir)
- l'acheteur intéressée envoie un mail  au vendeur avec ses coordonnées  via un bouton sur l'annonce.
- Pour éviter que les annonces des articles vendus reste affichée si le vendeur ne l'a pas supprimé, il faudra définir un temps de diffusion, au delà duquel on désactive l'annonce, et/ou on affiche un message au dépositaire de l'annonce pour confirmer est toujours d'actualité.

Qu'en pensez-vous ?

**Comment by VTTPierre** [comment]
Bonjour Patrick, 
Cela me semble une belle approche. 
Reste à voir quel type de photo (s) on autorise une ou plusieurs, critères minimum et maximum. 
L'idée restant plus sur la mise en contact entre deux adhérents. 
Je dirai une photo max et un descriptif en 200 caracteres max. 
Plus le prix et téléphone. 
Effectivement ne donner accès aux annonces qu'aux adhérents du club. 
Pour le reste il y a assez de sites leboncoin et autre. 
Ça tombe bien ton mail car hier lors de la sortie à champigneulles on a du ajouter un personne via le bouton ajouter un participant et il a été ajouté en doublon. 
Bonne journée 
Pierre 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : dimanche 11 juin 2023 07:34À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] Ajouter un encart Bonnes affaires ou Bourse d'échange, Seconde vie... (Issue #175)
Bonjour @VTTPierre @sylvainvtt,
On peut imaginer le système suivant

côté acheteur, on ajoute une rubrique, "mes annonces", comprenant  un formulaire pour déposer l'annonce avec son descriptif, une photo et son prix, avec possibilité de la modifier ou la supprimer.
à la création d'une nouvelle annonce, elle est envoyée à un modérateur qui doit valider pour la mettre en ligne.
les annonces sont visibles sur le site depuis une nouvelle rubrique accessible à tous ou uniquement aux personnes identifiées (à définir)
l'acheteur intéressée envoie un mail  au vendeur avec ses coordonnées  via un bouton sur l'annonce.
Pour éviter que les annonces des articles vendus reste affichée si le vendeur ne l'a pas supprimé, il faudra définir un temps de diffusion, au delà duquel on désactive l'annonce, et/ou on affiche un message au dépositaire de l'annonce pour confirmer est toujours d'actualité.

Qu'en pensez-vous ?

**Comment by pasojucle** [comment]
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/22dbf9fb-d3f4-4972-a00a-9e1455c053ee)
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/34f7494b-3416-44e2-8f8e-1f0834f5b3e6)
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/7e907c9a-3261-4705-b115-5142a317a5da)
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/1fe13d8c-96a1-4f23-aabd-71ae2bda2a79)
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/ac66a147-8194-4816-a8a9-15f543579ca6)
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/99870996-5185-42a8-8b0e-919fbf1a6d5a)
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/a7b5dba4-6de0-42aa-b9b2-ca77c6aeb687)
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/37f6cdcf-18cd-40f5-b217-7b6801d28f90)

**Comment by VTTPierre** [comment]
Bonjour Patrick,Cela me semble pas mal à première vue.Pourrons nous faire un point sur la façon de gérer ce pavé occasions.j'ai regardé sur le site de Test, je n'ai pas le pavé occasions.J'en profite pour te signaler que lorsque nous cherchons à modifier un contenu de la page d'accueil avec le MOBILE, la fenêtre est figée, pas possibilité de faire monter ou descendre la page.En pj une petite coquille inscriptionBonne journéeenvoyé : 27 août 2023 à 13:18de : pasojucle ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>cc : VTTPierre ***@***.***>, Mention ***@***.***>objet : Re: [pasojucle/vtt_evasion_ludres] Ajouter un encart Bonnes affaires ou Bourse d'échange, Seconde vie... (Issue #175)        —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by sylvainvtt** [comment]
Slt Patrick,Je ne sais pas si c'est prévu mais chaque dépose d'annonce devra étre validée par un administrateur avant diffusion.Merci et à ce soirSylvain Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 27/08/2023  13:18  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Ajouter un encart Bonnes affaires ou Bourse d'échange, Seconde vie... (Issue #175)

**Comment by VTTPierre** [comment]
Je pense effectivement qu'il faut valider par un admin. Reste à voir si on crée une adresse mail "Alias" pour ce point.envoyé : 28 août 2023 à 08:38de : sylvainvtt ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>cc : VTTPierre ***@***.***>, Mention ***@***.***>objet : Re: [pasojucle/vtt_evasion_ludres] Ajouter un encart Bonnes affaires ou Bourse d'échange, Seconde vie... (Issue #175) Slt Patrick,Je ne sais pas si c'est prévu mais chaque dépose d'annonce devra étre validée par un administrateur avant diffusion.Merci et à ce soirSylvain Envoyé depuis mon appareil Galaxy -------- Message d'origine --------De : pasojucle ***@***.***> Date : 27/08/2023 13:18 (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Ajouter un encart Bonnes affaires ou Bourse d'échange, Seconde vie... (Issue #175)           —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by pasojucle** [comment]
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/536c4d3c-da62-43a6-848e-aae2c0da6673)
