### ISSUE TITLE
doublon

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#176]
Bonjour Patrick,

En ajoutant manuellement un adhérent ou encadrant sans passer par son login mot de passe et tout, il se trouve que nous nous retrouvons avec un doublon dans la liste de présence.

pour exemple Laurent Fordoxcel sur le sortie du 20-05-2023

![doublon](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/af4fe8b2-4d4b-45c1-84f5-348540e2a20e)

**Comment by pasojucle** [comment]
Bonjour @VTTPierre, 
Si on ajoute un participant par la listes des groupes d'une sortie, le sélecteur ne propose que les adhérents qui ne sont pas déjà inscrit. Je viens de le tester sur la sortie du 27/05, ce n'est pas possible d'ajouter à nouveau les adhérents qui sont inscrits. Je ne comprend pas bien d'où peut provenir ces doublons !?!
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/8aba3d73-9682-4d70-966b-3db72a7d473a)

**Comment by VTTPierre** [comment]
Bonsoir Patrick, 
C'est effectivement le cas une fois l'adhérent ajouté il ne figure plus dans la liste, par contre j'ai eu ce cas sur 4 ajouts de 5 adhérents samedi dernier. Je ne vois pas ce qui provoque cela car j'attends d'avoir le message de confirmation qui s'efface entre chaque saisie. 
Sylvain avait également eu ce soucis il y a un moment. 
À suivre 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : lundi 22 mai 2023 20:52À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] doublon (Issue #176)
Bonjour @VTTPierre,
Si on ajoute un participant par la listes des groupes d'une sortie, le sélecteur ne propose que les adhérents qui ne sont pas déjà inscrit. Je viens de le tester sur la sortie du 27/05, ce n'est pas possible d'ajouter à nouveau les adhérents qui sont inscrits. Je ne comprend pas bien d'où peut provenir ces doublons !?!

**Comment by pasojucle** [comment]
Bonjours @VTTPierre, Je pensais quand revenant en arrière après l'inscription, on pouvais valider 2 fois, mais ce n'est pas le cas. J'ai donc modifié le code pour contrôler que l'adhérent ne soit pas déjà inscrit avant d'enregistrer l'inscription. Je refais une série de tests dans la semaine, et je met à jours le site dès que c'est bon, en espérant que ça va arranger le problème. A suivre ...

**Comment by VTTPierre** [comment]
Merci Patrick. 
C'est pas trop grave mais si on doit faire la promo du site à d'autres écoles cyclo il faut un truc nickel. 
Je plaisante ! 
Merci pour tout 
Bonne soirée 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : mardi 23 mai 2023 20:48À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] doublon (Issue #176)
Bonjours @VTTPierre, Je pensais quand revenant en arrière après l'inscription, on pouvais valider 2 fois, mais ce n'est pas le cas. J'ai donc modifié le code pour contrôler que l'adhérent ne soit pas déjà inscrit avant d'enregistrer l'inscription. Je refais une série de tests dans la semaine, et je met à jours le site dès que c'est bon, en espérant que ça va arranger le problème. A suivre ...

**Comment by VTTPierre** [comment]
Ce point semble OK à présent, nous n'avons pas eu de doublon lors d'ajout de jeunes depuis la rentrée de sept 2023
