### ISSUE TITLE
Inscription rando du dimanche

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#179]
En plus de choisir son groupe (1,2 ou3) à une rando du dimanche, ensuite il faudrait rajouter 4 choix : VTT musculaire, VTTAE, Route, Gravel.

**Comment by pasojucle** [comment]
@sylvainvtt Le type de vélo, c'est juste informatif ou c'est pour créer des groupes supplémentaires ?

**Comment by sylvainvtt** [comment]
Salut Patrick,C juste informatif.MerciSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 02/09/2023  08:58  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Inscription rando du dimanche (Issue #179) 
@sylvainvtt Le type de vélo, c'est juste informatif ou c'est pour créer des groupes supplémentaires ?

**Comment by pasojucle** [comment]
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/39ecdf94-7532-4d21-8c85-4eda4bc8e4ea)
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/ae31a9b5-0812-4e16-8bc2-5935937251ab)
