### ISSUE TITLE
impossible d'ajouter un nouvel adhérent 3 séances essais à la séance du jour

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#182]
Bonjour Patrick.
Samedi 09 nous avons été confronté à un soucis d'ajout de participants à la séance depuis le menu du jour.
En fait les personnes que l'on retrouve dans le pavé Inscription ne sont pas visible dans la liste des adhérents à ajouter dans la liste des participants.
Je pense que seuls les licenciés sont visibles dans la liste des participants à ajouter. Il faudrait pouvoir ajouter tous les inscrits en cours et ceux de la saison passée 2023.
J'ai créé un compte pour ma femme pas possible de l'ajouter via le module ajouter participant.
ci joint les diverses copies d'écrans.

Je reste à ta dispo si besoin de plus d'explications

![inscription](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/d6b05ab9-72be-402a-ac12-fedf9e5c15d6)

![adherents](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/ab53f164-0d95-4eb2-9a4c-83eec86dc6ee)

![ajout adherent](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/115e694c-8fa6-4700-9acd-7c54c90791ea)

**Comment by pasojucle** [comment]
Bonjour @VTTPierre . Les nouveaux  adhérents dont le dossier d'inscription n'est pas validé, ne remontaient pas dans le filtre. Je viens de modifier

**Comment by VTTPierre** [comment]
Merci Patrick. 
Pour le dossier de Tatiana je n'ai rien fait mais son dossier semble créé. 
À suivre. 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : mercredi 13 septembre 2023 16:00À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] impossible d'ajouter un nouvel adhérent 3 séances essais à la séance du jour (Issue #182)
Bonjour @VTTPierre . Les nouveaux  adhérents dont le dossier d'inscription n'est pas validé, ne remontaient pas dans le filtre. Je viens de modifier

**Comment by VTTPierre** [comment]
Le dossier de Tatiana est créé par contre ces deux séances d'essais ne sont pas comptabilisées. 
Idem pour Fordoxcel augustin2, créé à l'arrache car comme il était déjà dans les bases avec une licence en 2022, il ne pouvait pas faire une réinscription aux 3 séances d'essais. 
A voir comment on gère ces cas de personnes qui reviennent après une coupure d'un ou deux ans.
