### ISSUE TITLE
affichage mes sorties programme perso

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#190]
Patrick,

Peux tu voir pour avoir un classement par date dans l'affichage du programme perso.

Ci dessous la sortie du 14 octobre est avant celle du 08 et du 01.
En fait l'affichage actuel se fait dans l'ordre de saisie et non par l'ordre chronologique habituel.

![ordre des sorties programme perso](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/d1d41aee-ea06-4510-81e9-447dfe7a17fb)

**Comment by pasojucle** [comment]
Bonjour @VTTPierre. Cette modification a déjà été faite sur le site de test
