### ISSUE TITLE
Annonce

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#191]
Après les lignes d'information du club concernant les responsabilités, il faudrait mettre une case à cocher qui confirme que la personne à bien lu ces informations. Tant que la case n'est pas cochée, le formulaire reste grisé et ne peut être rempli. Si la case est décochée après avoir rempli l'annonce, tout redevient grisé et ne peut-être envoyé.

**Comment by pasojucle** [comment]
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/84365c37-e4fe-4be4-b138-13aa71397d72)<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/8df31092-2ad3-4b5c-b1a9-cadc8b668d3a)

**Comment by sylvainvtt** [comment]
Merci Patrick.Tu peux enlever l'accent sur "j'accepte" 🙈J'ai reçu le doc assurance 2024 et les nouveautés pour l'inscription.Bonne soiréeSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 11/10/2023  19:29  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Author ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Annonce (Issue #191)
