### ISSUE TITLE
Pouvoir administrer les ré-inscriptions

### ISSUE THREAD

**Issue by pasojucle** [pasojucle/vtt_evasion_ludres#199]
Pour éviter que les membres inscrits sur la saison en cours, s'inscrivent pour la saison à venir dès la rentrée de septembre,  je propose d'ajouter un paramètre pour activer ou désactiver les ré-inscriptions.

- lorsque le paramètre est désactivé, on affiche un message quand un membre tente de s'inscrire à la prochaine saison, pour l'informer que sa licence cours jusque au 31 décembre, et que l'inscription pour l'année suivant se fera à partir du 1er décembre
- lorsque la ffvélo met à disposition le pdf des licences pour la nouvelle année, on active le paramètre
- lorsqu'on active, une pop'up averti les membres que les ré-inscriptions sont possible

@sylvainvtt qu'en penses-tu ?

**Comment by sylvainvtt** [comment]
Slt Patrick,Beau temps pour bosser à la maison 😁Oui bonne idée. Mais ne pas mettre de date ds le texte du pop up. Mettre :...... suivante se fera prochainement.Sinon, nickel.Merci et bon dimancheSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 05/11/2023  13:39  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : [pasojucle/vtt_evasion_ludres] Pouvoir administrer les ré-inscriptions (Issue #199) 
Pour éviter que les membres inscrits sur la saison en cours, s'inscrivent pour la saison à venir dès la rentrée de septembre,  je propose d'ajouter un paramètre pour activer ou désactiver les ré-inscriptions.

lorsque le paramètre est désactivé, on affiche un message quand un membre tente de s'inscrire à la prochaine saison, pour l'informer que sa licence cours jusque au 31 décembre, et que l'inscription pour l'année suivant se fera à partir du 1er décembre
lorsque la ffvélo met à disposition le pdf des licences pour la nouvelle année, on active le paramètre
lorsqu'on active, une pop'up averti les membres que les ré-inscriptions sont possible

@sylvainvtt qu'en penses-tu ?

**Comment by pasojucle** [comment]
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/6a6a7277-f2bf-462a-a589-21a2efab914b)
<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/5c242a21-0085-454c-b196-799a7b7b08b0)
<br>
**Lorsque que l'adhérent s’inscrit alors que le paramètre est désactivé**
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/fcbdf17d-6605-4d84-97de-95207068ee71)
<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/b80a77a6-58eb-41a5-baf9-894936cf47d2)
<br>
**Lorsque que l'adhérent se connecte alors que le paramètre est activé**
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/2da3440d-2e8e-4aa9-84f2-80cd9772f884)

**Comment by sylvainvtt** [comment]
Slt Patrick,Impeccable, merci. C'est bien parlant comme ça.Bonne journéeSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 14/12/2023  21:15  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Pouvoir administrer les ré-inscriptions (Issue #199) 
image.png (view on web)

image.png (view on web)

Lorsque que l'adhérent s’inscrit alors que le paramètre est désactivé
image.png (view on web)

image.png (view on web)

Lorsque que l'adhérent se connecte alors que le paramètre est activé
image.png (view on web)

**Comment by pasojucle** [comment]
Bonjour @sylvainvtt . Je mettrai le site à jour ce soir, comme ça le message s'affichera pour ceux qui ne ce sot pas encore réinscrit. Je l'ai déjà mis sur les site de test, si tu veux voir. c'est ok pour toi ?

**Comment by sylvainvtt** [comment]
Salut Patrick,J'ai vu les messages sur le mail que tu avais envoyé. C'est tout bon, tu peux y aller.Merci et bon dimancheSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 16/12/2023  08:04  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Pouvoir administrer les ré-inscriptions (Issue #199) 
Bonjour @sylvainvtt . Je mettrai le site à jour ce soir, comme ça le message s'affichera pour ceux qui ne ce sot pas encore réinscrit. Je l'ai déjà mis sur les site de test, si tu veux voir. c'est ok pour toi ?
