### ISSUE TITLE
Exporter la participation par date 

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#200]
Patrick,

Serait-il possible de faire en sorte que l'on puisse exporter la participation à l'encadrement. Si possible sur une année civile et/ou sur une saison.
Le filtre type de sortie doit rester comme il est.
Peut être ajouter Année civile 2024, Année civile 2023, Année civile 2022, Année civile 2021 dans la section saison.
A défaut pouvoir faire un export global de toutes les participations de tout le monde sur une année ou une saison.

![participation](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/7e358505-21b0-476f-b733-e68905085cc8)

**Comment by VTTPierre** [comment]
Patrick, 

Après en avoir discuté avec Sylvain, il serait plus judicieux de faire une date de début et date de fin pour la sélection et l'export.  On abandonne l'idée de saison ou année

Cdt
Pierre

**Comment by pasojucle** [comment]
@VTTPierre , @sylvainvtt, Je peux vous proposer de faire une page uniquement pour la participation, avec le même filtre que sur la liste des adhérents, et remplacer le filtre sur la saison, par le choix de la période, et un bouton pour exporter la liste filtrée.<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/fa5048c6-d083-4b99-b627-43929320cbe1)<br>
Qu'en pensez-vous ?

**Comment by pasojucle** [comment]
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/df5f0273-d78d-42d3-85b4-ea381298ebcc)

**Comment by pasojucle** [comment]
[export_participation_751859 (1).csv](https://github.com/pasojucle/vtt_evasion_ludres/files/13466130/export_participation_751859.1.csv)

**Comment by VTTPierre** [comment]
Parfait.. 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : dimanche 26 novembre 2023 08:07À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] Exporter la participation par date (Issue #200)
export_participation_751859 (1).csv
