### ISSUE TITLE
Limiter accès aux licenciés année N en cours

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#201]
Voir comment faire pour laisser accès aux seuls licenciés à jour de leur cotisation sur l'exercice en cours.
Cela concernerait l'onglet Annonce, Boutique, Documentation de l'École VTT …
A voir si on applique sur d'autres thèmes.

**Comment by pasojucle** [comment]
Bonjour @VTTPierre, le paramétrage des droits sur le site est réparti en 5 secteurs: les inscriptions au sorties, la boutique, l'occasion, et les dossiers d'inscription. Aujourd'hui, je regarde si l'utilisateur est loggé, mais je peux facilement ajouter à la règle de vérifier qu'il ai une licence de la saison en cours. On peut aussi créer des règles supplémentaires, pour la documentation par exemple

**Comment by pasojucle** [comment]
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/9026542b-da29-40f1-bf0e-94a56da68f85)
<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/153d0926-95c8-4f14-9d55-27d526d7c4ac)
<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/900360ef-5e18-48b2-988b-fc407855b4a6)
<br>

**Comment by pasojucle** [comment]
Bonjour @VTTPierre . Le site est à jour de tous les développements qui ont été fait depuis septembre sauf celui-ci que je viens de mettre sur le site de test
