### ISSUE TITLE
Améliorations à l'inscription à une sortie

### ISSUE THREAD

**Issue by pasojucle** [pasojucle/vtt_evasion_ludres#203]
1.  Quand une personne s'inscrit pour une sortie (jeunes et adultes) il faudrait qu'au moment de valider, un pop'up s'affiche avec ce texte "Il est impératif de se désinsrire si vous ne participez pas à cette sortie (voir dans Mon programme perso et faire "se désinscrire ").
2.  Quand une personne s'est inscrite à une sortie, il faudrait que dans le programme le bouton "s'inscrire" se transforme en "se désinscrire".

**Comment by pasojucle** [comment]
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/22e7e72f-8715-4d47-8d6f-c843dfdab9d1)<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/6b24c730-a18f-4b29-a613-ce8b705bc41c)

**Comment by pasojucle** [comment]
@sylvainvtt Est-ce qu'on affiche la pop'up pour tout le monde ou uniquement aux jeunes pour sorties de l'école vtt (hors encadrants) ?

**Comment by sylvainvtt** [comment]
Ça concernait quoi déjà ? 🤔Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 16/12/2023  19:26  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Améliorations à l'inscription à une sortie (Issue #203) 
@sylvainvtt Est-ce qu'on affiche la pop'up pour tout le monde ou uniquement aux jeunes pour sorties de l'école vtt (hors encadrants) ?
