### ISSUE TITLE
Ajouter Programme dans admin Alain GASC

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#206]
Patrick,

J'ai échangé avec Alain GASC ce jour et il n'a plus accès à la page programme dans l'admin, lui laisser les accès actuels:

Adhérents
Inscription
Assurance

et ajouter 
Programme 

![ajout programme alain](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/169a214b-7012-47f6-8967-8d995a799908)

**Comment by pasojucle** [comment]
Bonjour @VTTPierre.  Dans la fiches des adhérents, les admins peuvent gérer le droits. Je vient d'activer l'accès au programme et aux groupes pour Alain.
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/ad7d7a35-99d9-4fb8-9f2e-864bf9811d96)

**Comment by VTTPierre** [comment]
Merci Patrick 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : mercredi 13 décembre 2023 18:36À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] Ajouter Programme dans admin Alain GASC (Issue #206)
Bonjour @VTTPierre.  Dans la fiches des adhérents, les admins peuvent gérer le droits. Je vient d'activer l'accès au programme et aux groupes pour Alain.
image.png (view on web)
