### ISSUE TITLE
Agé maxi pour sortie 

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#207]
Patrick

Serait-il possible de faire un second bouton pour imposer un âge maximum sur la création d'une sortie.
Pour exemple pour le CDER à Maxéville les jeunes doivent avoir 12 ans au plus.

Sinon faire un sélecteur adhérents nés entre **/**/**** et  **/**/****

![age maxi](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/e3119bc0-7925-4f59-b22d-9b5a7bc97eef)

**Comment by pasojucle** [comment]
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/a5889bd4-d70c-451d-a8a1-ceeb7f849145)

**Comment by VTTPierre** [comment]
Merci pour cette proposition. 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : lundi 01 janvier 2024 18:20À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Author ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] Agé maxi pour sortie  (Issue #207)
image.png (view on web)
