### ISSUE TITLE
Comptage des inscrits et participants sur tableau de bord

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#229]
Petit décalage de comptabilisation sur les volumes sur le tableau de bord.
En fait tout est comptabilisé, même les absents.  
Par exemple aujourd'hui Brasseur Adeline n'a pas roulé. pourtant elle est comptabilisé dans les 37 alors que nous étions 24 jeunes et 12 adultes ou vieux.
A voir si laisse en l'état ou non. 
![30 03 2024_19 10 00_REC](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/feab1943-8e45-4667-82c1-0bd113028a03)

**Comment by pasojucle** [comment]
Bonjour @VTTPierre. Après vérification il y a bien 37 présents

Les Petits Loups : 7
Les Renards : 6
Les Chamois : 9
Les Bouquetins : 6
Les Sangliers : 9

Total : 37
![Screenshot 2024-03-31 at 07-15-17 ÉcoleVTT](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/79d10df3-6b30-441c-83b5-e2e19e854a1e)

**Comment by VTTPierre** [comment]
Bonjour Patrick,Effectivement le compte est bon.J'avais une petite coquille dans mon import vers Excel. Tout est ok à présent.Désolé pour ce faux ticket.envoyé : 31 mars 2024 à 07:23de : pasojucle ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>cc : VTTPierre ***@***.***>, Mention ***@***.***>objet : Re: [pasojucle/vtt_evasion_ludres] Comptage des inscrits et participants sur tableau de bord (Issue #229) Bonjour @VTTPierre. Après vérification il y a bien 37 présentsLes Petits Loups : 7 Les Renards : 6 Les Chamois : 9 Les Bouquetins : 6 Les Sangliers : 9Total : 37 Screenshot.2024-03-31.at.07-15-17.EcoleVTT.png (view on web)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
