### ISSUE TITLE
bloquer une sortie  URGENT

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#231]
Bonjour Patrick,

Serait-il possible de bloquer la sortie du séjour Vosges afin que plus personne ne puisse s'inscrire et surtout se DESINSCRIRE.
Pour bloquer l'inscription il suffit de changer la date de fin ce que j'ai fait.

Par contre l'idée et de ne pas pouvoir se désinscrire sans préavis ou prise de contact avec le club. 
Bref il faudrait pouvoir bloquer le panier de l'adhérent. Car une fois que la rando est dans son programme il peut se désinscrire librement. Pour une rando du dimanche ou une école vtt du samedi ce n'est pas trop grave. Par contre lorsque nous avons des engagements avec l'extérieur il faudrait pouvoir bloquer une sortie en désinscription avec un bouton bloquer la sortie ou autre .

![sortie vosges](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/4bef0541-63a9-474d-a146-ebce3ca5f25b)

**Comment by pasojucle** [comment]
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/c3a50ab4-d9c9-4472-8833-ac8d5b3b1a14)
<br>![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/f611c0ae-7a26-4b80-9bf8-066e338a922e)
<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/7994e7c2-1e3d-4900-84c0-7e06d5c4f02b)
<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/2dfbf9e2-c199-4fc1-b46b-dcddb3649b63)
