### ISSUE TITLE
bugg supprimer dossier photo 

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#232]
Patrick, en voulant supprimer un dossier photos j'ai un fatal error

serait-il possible de pouvoir importer un dossier de phots, plutôt que les photos une à une.

https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/60f9b2be-fef3-4a48-a5e9-96e168338231

**Comment by VTTPierre** [comment]
Fausse alerte ou presque, 
En fait il faut supprimer les photos une à une du dossier et ensuite on peut supprimer le dossier. 
Donc il faudrait étudier le fait de pouvoir gérer par dossier plutôt que par photo.

 Á suivre

**Comment by pasojucle** [comment]
Bonjour @VTTPierre. Je viens de corriger le bug pour la suppression d'un répertoire qui contient des photos. Pour le téléchargement, tu peux télécharger plusieurs fichiers en même temps en glissant les photos de ton ordi sur le sites, mais un seul par le bouton. On est juste limité à un certain volume de données en téléchargement (à prioris upload_max_filesize = 64M sur ionos).

**Comment by VTTPierre** [comment]
ok merci Patrick pour ton retour, j'avais oublié le sélectionner glisser déposer.On va limiter en taille de fichier et retailler à la hache pour que cela passe.Bonne soiréeenvoyé : 16 avril 2024 à 18:56de : pasojucle ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>cc : VTTPierre ***@***.***>, Mention ***@***.***>objet : Re: [pasojucle/vtt_evasion_ludres] bugg supprimer dossier photo (Issue #232) Bonjour @VTTPierre. Je viens de corriger le bug pour la suppression d'un répertoire qui contient des photos. Pour le téléchargement, tu peux télécharger plusieurs fichiers en même temps en glissant les photos de ton ordi sur le sites, mais un seul par le bouton. On est juste limité à un certain volume de données en téléchargement (à prioris upload_max_filesize = 64M sur ionos).—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by pasojucle** [comment]
@VTTPierre l'espace disque est de 100g, et 64m par téléchargement

**Comment by pasojucle** [comment]
@VTTPierre Petite précision : les fichiers importé sont redimensionnés en HD soit 1920x 1080px.<br>
Mais pour la jauge, c'est faisable

**Comment by VTTPierre** [comment]
J'ai dimensionné en masse avant d'importer 
Donc pas de souci 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : mercredi 17 avril 2024 19:23À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] bugg supprimer dossier photo (Issue #232)
@VTTPierre Petite précision : les fichiers importé sont redimensionnés en HD soit 1920x 1080px.
Mais pour la jauge, c'est faisable

**Comment by VTTPierre** [comment]
Patrick,

Nouveau petit dysfonctionnement de la partie diaporama.
J'ai voulu retirer des photos du diaporama de la rando 2024 mais le site n'en tient pas compte. Du coup j'ai supprimé toutes les photos du dossier L'Évasion_2024. Elle ne sont plus dans le dossier diaporama de la partie Admin. Par contre elles restent visible sur le site lorsque l'on fait défiler les photos.  Mystère !!

https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/97c7f962-e0c2-4ce3-8a17-bbdee7f3187e

Nous ne devrions plus n'avoir que 4 photos dans le diaporama, or y'en a plus de 40.

**Comment by pasojucle** [comment]
Bonjour @VTTPierre. Les problèmes de suppression de dossier et d'images sont corrigés.<br>
J'ai ajouté également une jauge pour voir l'espace disque occupé par le diaporama. J'ai arbitrairement mis 20G max, mais cette valeur est paramétrable. A 85% d'espace occuper par rapport à cette valeur, la jauge passe au rouge. A 100%, on ne peut plus télécharger d'images.<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/b121fe4d-b8a4-4709-a2d9-b21c3c239733)
<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/ff0e6836-cf66-4e32-826e-5734a549a43b)

**Comment by VTTPierre** [comment]
Vraiment trop fortTu as vu j'ai fait de la pub pour le diaporama et pour les annonces d'occasion. petit pop-upEncore merci. On a une petite réunion club ce soir, je vais pouvoir frimer.Je crois qu'on a bien de profiter le week-end dernier, ce ne sera pas si cool au vide grenier ce w-eA très bientôtenvoyé : 19 avril 2024 à 18:26de : pasojucle ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>cc : VTTPierre ***@***.***>, Mention ***@***.***>objet : Re: [pasojucle/vtt_evasion_ludres] bugg supprimer dossier photo (Issue #232) Bonjour @VTTPierre. Les problèmes de suppression de dossier et d'images sont corrigés. J'ai ajouté également une jauge pour voir l'espace disque occupé par le diaporama. J'ai arbitrairement mis 20G max, mais cette valeur est paramétrable. A 85% d'espace occuper par rapport à cette valeur, la jauge passe au rouge. A 100%, on ne peut plus télécharger d'images. image.png (view on web)  image.png (view on web)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by VTTPierre** [comment]
Bien vu pour la jauge, Encore une petite demande de confort, possibilité d'indiquer le nombre d'éléments d'un dossier en le sélectionnant ?Oui je sais on va exploser le budget développement se semestre.envoyé : 19 avril 2024 à 18:26de : pasojucle ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>cc : VTTPierre ***@***.***>, Mention ***@***.***>objet : Re: [pasojucle/vtt_evasion_ludres] bugg supprimer dossier photo (Issue #232) Bonjour @VTTPierre. Les problèmes de suppression de dossier et d'images sont corrigés. J'ai ajouté également une jauge pour voir l'espace disque occupé par le diaporama. J'ai arbitrairement mis 20G max, mais cette valeur est paramétrable. A 85% d'espace occuper par rapport à cette valeur, la jauge passe au rouge. A 100%, on ne peut plus télécharger d'images. image.png (view on web)  image.png (view on web)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by pasojucle** [comment]
@VTTPierre C'est cadeau !!<br>
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/bd8b40c2-250e-439e-b38c-a361b06f82a1)

**Comment by VTTPierre** [comment]
Tu es terrible Patrick. 
Merci pour tout. 
On te verra au vide grenier dimanche. 
Bon week-end 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : samedi 20 avril 2024 07:31À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] bugg supprimer dossier photo (Issue #232)
@VTTPierre C'est cadeau !!
image.png (view on web)
