### ISSUE TITLE
doublon de sortie dans tableau de bord

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#239]
affichage tableau de bord, petit bugg de doublon la sortie du 8 juin est en double

La sortie inter-école apparait deux fois.

Malgré un refresh et vidage de cache

![prog juin](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/95eb228d-16f4-4949-bc08-97a1c9fb3657)
![bugg tableau de bord](https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/035ab1a8-a83b-4105-bfe5-40dd302d0f04)

**Comment by pasojucle** [comment]
Bonjour @VTTPierre. C'est une rando qui a été supprimée. C'est juste un flag dans la base de donnée et ma requête n'en tenait pas compte. C'est corrigé.

**Comment by VTTPierre** [comment]
Merci Patrick. 
Effectivement la sortie était prévu sans inter-école mais le calendrier en a décidé autrement. 
Pas de soucis 
Bonne soirée 
 
Envoyé depuis l'application Mail Orange
----------------De : pasojucle ***@***.***>Envoyé : lundi 03 juin 2024 18:30À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : VTTPierre ***@***.***>; Mention ***@***.***>Objet : Re: [pasojucle/vtt_evasion_ludres] doublon de sortie dans tableau de bord (Issue #239)
Bonjour @VTTPierre. C'est une rando qui a été supprimée. C'est juste un flag dans la base de donnée et ma requête n'en tenait pas compte. C'est corrigé.
