### ISSUE TITLE
Renouvellement de licence

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#243]
Possibilité de renouveler sa licence dans le menu "mes infos" directement par un bouton. Au même endroit que "modifier mon mot de passe" et "télécharger mon dossier".

**Comment by pasojucle** [comment]
Lorsque le paramètre pour autoriser les réinscriptions, les adhérents auront une pop up à chaque connexion pour les inciter à se réinscrire.

**Comment by sylvainvtt** [comment]
Salut Patrick,Il va falloir autoriser les réinscriptions maintenant. Est-ce que la nouvelle version est bien stable pour les réinscriptions ou faut-il assurer avec l'ancienne version et passer à la màj plus tard ?Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 09/11/2024  07:54  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Author ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Renouvellement de licence (Issue #243) 
Lorsque le paramètre pour autoriser les réinscriptions, les adhérents auront une pop up à chaque connexion pour les inciter à se réinscrire.
