### ISSUE TITLE
calcul des indemnités pour renouvellement de licences encadrement.

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#248]
Patrick,

Comment savoir sur quelles dates le calcul des indemnités est paramétré. 
01 septembre au 31 Aout de l'année N-1  ?
A voir avec Sylvain pour définir les dates.
Où trouver l'info dans l'outil pour savoir comment cela est réglé.

**Comment by pasojucle** [comment]
Bonjour @VTTPierre , 

Les indemnités sont calculées sur la période d'une saison, qu 1/09 au 31/08.
Il y a paramètre pour définir le début de la saison, via le menus Inscrition/Date du début de la nouvelle saison

![image](https://github.com/user-attachments/assets/c92efddf-604b-45ea-8ed0-f4ca7212a409)
