### ISSUE TITLE
Indicateur d'évaluation sur une séance.  ainsi qu'un export des évaluations

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#259]
Avoir un indicateur de Evaluation à faire sur une séance

![indic eval](https://github.com/user-attachments/assets/a1949a79-b658-4dac-8b1f-040341bc1009)

Egalement prévoir un export des évaluations par groupe de niveau ou par séance. A discuter

**Comment by VTTPierre** [comment]
Export des évaluations de tous les jeunes de l'école depuis la liste des compétences

**Comment by pasojucle** [comment]
![image](https://github.com/user-attachments/assets/9103e41d-ff6d-4b1c-a17b-e5facc24dfa0)<br>

![image](https://github.com/user-attachments/assets/529797f9-60ed-4771-bf32-5fd9316790ed)<br>
