### ISSUE TITLE
Gestion des adhérents

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#30]
1) Je pense qu'il faut revoir (encore !) le 1er menu déroulant : 
Tous
**Licences**
    Actives
    En attente renouvellement
    Non renouvelées
    3 séances en cours
    3 séances finies
2) Dans la fiche d'un adhérent, est-ce que le champs "Période de 3 séances de test" pourrait passer de "en cours" à "terminé"  dès que 3 séances faites (à mesure des pointage de présence aux séances) , mais pouvoir quand-même l'actionner manuellement ?
3) Si une personne crée une inscription aux 3 séances, il devrait être dans la gestion des adhérents SEULEMENT après s'être inscrit à une séance d'école du samedi ou adulte le dimanche (sinon on a plein de fiches qui ne servent à rien). En attendant on garde juste le dossier, c'est tout.
4) Il faut qu'un adulte en 3 séances d'essai puisse s'inscrire aussi (comme adulte) à une séance de l'école.

**Comment by VTTPierre** [comment]
![Gestion_adhérents](https://user-images.githubusercontent.com/87672341/131548168-52b6c93d-6033-4fe2-a382-7bd01883a829.png)
