### ISSUE TITLE
Dossier d'inscription

### ISSUE THREAD

**Issue by sylvainvtt** [pasojucle/vtt_evasion_ludres#35]
Il faudrait un champs pour un n° de tél à prévenir en cas d'urgence, mais uniquement pour les adultes (on a déjà les contacts pour les jeunes).

**Comment by pasojucle** [comment]
![controle date naissance](https://user-images.githubusercontent.com/54477272/160293335-cb051f18-d076-413c-bd0d-36914c1ef5ac.png)
![controle nom](https://user-images.githubusercontent.com/54477272/160293338-1be3322d-da6c-4536-8fc1-582710d20771.png)
[inscription_essai_adulte.pdf](https://github.com/pasojucle/vtt_evasion_ludres/files/8358128/inscription_essai_adulte.pdf)
[inscription_essai_mineur.pdf](https://github.com/pasojucle/vtt_evasion_ludres/files/8358130/inscription_essai_mineur.pdf)
[inscription_finale_adulte.pdf](https://github.com/pasojucle/vtt_evasion_ludres/files/8358131/inscription_finale_adulte.pdf)
[inscription_final_mineur.pdf](https://github.com/pasojucle/vtt_evasion_ludres/files/8358132/inscription_final_mineur.pdf)
