### ISSUE TITLE
Ajout d'une page ( La Boutique)

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#39]
Patrick!

Une nouvelle demande 'URGENTE' à la veille de l'ouverture.

Créer une page "La Boutique" l'idée et de juste mettre en place le bouton qui envoi sur une page.

![30 08 2021_13 36 56_REC](https://user-images.githubusercontent.com/87672341/131349007-a58c8454-dca2-4ae1-b2de-cac183d9b3b5.png)

laisser la possibilité de mettre un document type PDF indiquant  "en construction ouverture prochaine de votre boutique"

Ca c'est pour l'urgence du moment.
_______________________________________________________________________________________________________________________________

Ensuite il faudra réfléchir ensemble comment gérer cette boutique.
L'idée serait de ne laisser accès aux commandes qu'aux adhérents du club via un formulaire. 
Laisser le visuel de la boutique ouvert à tous, sans indication de tarif.
Si la personne veut commander via le bouton "Commander", il faudra qu'elle s'identifie et elle aura la page des articles avec taille et tarif pour passer sa commande.

Bon courage
@Pierre

**Comment by VTTPierre** [comment]
Corriger Progra**_m_**me du club

**Comment by pasojucle** [comment]
- titre
- descriptif
- image
- taille
- quantité 
- prix

**Comment by pasojucle** [comment]
faire un export avec le récap de toutes les commandes
