### ISSUE TITLE
Refonte page mon compte

### ISSUE THREAD

**Issue by pasojucle** [pasojucle/vtt_evasion_ludres#4]
Afficher dans le bloc de droite les infos des prochaines sorties auxquelles l'adherent s'est inscrit,  avec un bouton pour se désinscrire 
Pour un encadrant,  afficher toutes les sorties école vtt dont il a renseigné  sa dispo,  avec un bouton pour la modifier

Dans le bloc de gauche, ajouter des infos sur la licence, un bouton pour s'inscrire selon le cas, après la période d'essai par exemple

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/126903324-8a2d4eea-32c2-4106-89e3-b0448309f15a.png)

**Comment by sylvainvtt** [comment]
@pasojucle : dans le dossier d'inscription aux 3 séances, dans Droit à l'image, il ressort le nom de quelqu'un d'autre, en l'occurence "Levaisque Michèle"
