### ISSUE TITLE
Erreur 500 visualisation du programme "P1"

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#46]
![erreur_500_visu_prog](https://user-images.githubusercontent.com/87672341/131674650-4f50e3d9-f66f-43f8-bdef-f0a110c4211e.png)

En me connectant avec mon compte j'ai une erreur 500 lors de la visualisation du programme

**Comment by pasojucle** [comment]
Bonjour @pierre. J'ai supprimé l'inscription à la rando que l'on a fait hier avec le compte webmaster, et ça re-fonctionne.
