### ISSUE TITLE
accéder à la liste des encadrants présents

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#5]
Bonjour Patrick,

1. Comment faire pour visualiser les encadrants présents:
par exemple avec la coche verte et la croix rouge (cf pièce jointe)
![23 07 2021_08 00 10_REC](https://user-images.githubusercontent.com/87672341/126743980-27cf8e15-f17f-4048-8329-69a5b7d5980b.png)

@Pierre

**Comment by pasojucle** [comment]
On affiche la disponibilité de l'encadrant
Pour pointer les présence, j'ai juste mis un bouton ckeck qui devient vers lorsque l'on pointe la présence
![image](https://user-images.githubusercontent.com/54477272/126905256-d1fa9f1e-b0a8-4e98-9436-278de3527e61.png)
