### ISSUE TITLE
info autorisé à rentrer seul à la maison

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#50]
Bonjour Patrick

Mettre à disposition des encadrants, Moniteur-Initiateur l'information sur l'autorisation de pouvoir rentrer seul à la maison.

@Pierre

PS: reste également à corriger mo**n** mot de passe au lieu de mo**m** mot de passe

**Comment by pasojucle** [comment]
@VTTPierre 
J'ai mis l'info sur la fiche de l'adhérent
![Capture d’écran du 2021-09-10 19-18-51](https://user-images.githubusercontent.com/54477272/132892811-abeeeff0-3b7d-4086-87a1-a442851ae990.png)
![Capture d’écran du 2021-09-10 19-20-12](https://user-images.githubusercontent.com/54477272/132892815-1900dd29-0437-467c-98f9-7a8e6ce74c86.png)

**Comment by VTTPierre** [comment]
Je reviens à la charge avec ce point que j'ai clos, 
Serait -il envisageable d'avoir l'info de façon plus simple et directe à savoir un petite icone sur le nom du jeune.

Rouge pas autorisé , Vert autorisé
ou simplement non autorisé ROUGE.
Si trop compliqué , souligné le nom du jeune non autorisé. Ajouter une étoile après le prénom
Je ne sais pas ce qui pourrait être mis en place , mais l'idée est d'avoir un visuel simple pour ne pas devoir ouvrir la fiche de chaque jeune.

![autorisation_retour seul](https://user-images.githubusercontent.com/87672341/132914416-ef7c10a0-a356-4f66-9340-6e6487f0d835.png)
