### ISSUE TITLE
PASde visibilité des encadrants non dispo ou absent  PRIO_1

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#51]
Bonjour Patrick

J'ai fait une relance hier auprès des encadrants pour savoir s'ils sont dispo ou non.
Le souci reste que la notion de disponible et non disponible ne s'affiche pas dans le récap de la séance.
Cas de Laurent BEYER qui est absent samedi 11/09. il est bien noté non dispo sur sa fiche personnelle.

![non dispo non visible_](https://user-images.githubusercontent.com/87672341/132640183-077599d5-e2f5-40d2-8d3e-5a4f7f9f0237.png)

Egalement non dispo sur sa propre page d'inscription

![non dispo non visible](https://user-images.githubusercontent.com/87672341/132640303-c8ef64c0-f922-4d55-aeac-d8f3aa4b52c9.png)

Par contre dans le récap global de la sortie seuls les inscrits restent visible.

![non dispo non visible__](https://user-images.githubusercontent.com/87672341/132640474-d05d0b03-6338-4c22-afcc-f8328d105053.png)

**Comment by VTTPierre** [comment]
Seul de moyen d'avoir une vision globale, il faut revenir sur sa fiche et modifier son choix. Prendre le crayon sur la séance en question.


![__non dispo non visible](https://user-images.githubusercontent.com/87672341/132641230-80644ee1-09a5-4121-8eed-a6fd45ac4d9c.png)

![non dispo non visible_____](https://user-images.githubusercontent.com/87672341/132641359-704937ba-3a21-47d3-bbf2-3c1f10bd30cb.png)

**Comment by pasojucle** [comment]
@pierre
Les encadrants non disponibles ne sont pas visibles sur le détail d'une sortie, mais ceux qui se sont mis en "disponibilité" y sont, car c'est ceux là que tu peux appeler si tu as besoin d'encadrant supplémentaires.
Faut-il vraiment afficher ceux qui seront absent, alors que la liste une fois que tout le monde est inscrit est plutôt longue ?

**Comment by VTTPierre** [comment]
Bonsoir Patrick,
 
Je rentre à l'instant je vais regarder tous mes mails.
Effectivement on laisse comme ça pour le moment. 
Je voulais juste savoir comment je pouvais regarder que les encadrants ont pris position sur la séance à venir. 
J'ai trouvé un moyen de voir qui a fait son choix ou validé sa dispo ou non.
 
Cordialement
Pierre ALBRECHT
 
 
 
 
 
 
> Message du 10/09/21 18:51> De : "pasojucle" > A : "pasojucle/vtt_evasion_ludres" > Copie à : "VTTPierre" 
, "Author" > Objet : Re: [pasojucle/vtt_evasion_ludres] PASde visibilité des encadrants non dispo ou absent  PRIO_1 (#51)> >
>
> @pierre> Les encadrants non disponibles ne sont pas visibles sur le détail d'une sortie, mais ceux qui se sont mis en "disponibilité" y sont, car c'est ceux là que tu peux appeler si tu as besoin d'encadrant supplémentaires.> Faut-il vraiment afficher ceux qui seront absent, alors que la liste une fois que tout le monde est inscrit est plutôt longue ?
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/pasojucle/vtt_evasion_ludres/issues/51#issuecomment-917053238", "url": "https://github.com/pasojucle/vtt_evasion_ludres/issues/51#issuecomment-917053238", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by VTTPierre** [comment]
on laisse comme c'est. 
ne pas surcharger la liste.
