### ISSUE TITLE
desinscrire un adhérent Last minute

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#52]
Petit soucis que vient de me signaler sylvain, comment retirer un jeune qui s'est inscrit mais ne peut plus modifier son choix du fait qu'on interdit toute connexion à la séance 48h avant la séance.

- soit créer un bouton supprimer inscription

- créer un groupe annulé mais cela va charger le tout

- créer un bouton accessible uniquement à Sylvain et moi pour pouvoir annuler l'inscription à la séance de cet adhérent suite à un mail ou sms de dernière minute

![supprimer inscription last minute](https://user-images.githubusercontent.com/87672341/132912261-2962c599-83a4-4eb1-91d6-53ac1cbdb0d3.png)

- autre solution créer un bloc note ou autre champ libre pour pouvoir annoter l'info.

pas simple , à étudier, méditer et voir comment partager l'info

**Comment by pasojucle** [comment]
@VTTPierre @sylvainvtt
Un adhérent peut à tout moment se désinscrire à une rando en se connectant à son compte, dans mes randos. Il n'y a pas de contrôle sur les dates.
![Capture d’écran du 2021-09-11 12-54-47](https://user-images.githubusercontent.com/54477272/132945557-183ed0d3-5f86-4319-91de-ca1dd46b2a9e.png)

**Comment by VTTPierre** [comment]
ok pour laisser comme c'est.  
Il conviendra juste de corriger deux petites fautes. 

![je confirme me désinscrire](https://user-images.githubusercontent.com/87672341/133332875-45a54b22-903f-4dd1-8007-3348e143f558.png)

![désinscription](https://user-images.githubusercontent.com/87672341/133332888-bf75947c-e4a0-4a2d-b43a-b041505cedd3.png)
