### ISSUE TITLE
Impossibilité de supprimer une sortie  (non urgent)

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#57]
Impossible de supprimer de sortie ou annuler une sortie

A discuter avec Sylvain.

![programme_sortie non annulable_1](https://user-images.githubusercontent.com/87672341/133885590-623a176d-5e2b-4065-847c-5ba5b75b192d.png)

Avoir un bouton pour annuler ou supprimer une sortie

![programme_sortie non annulable_2](https://user-images.githubusercontent.com/87672341/133885594-4ab0f7a6-b246-47c8-a711-7bd431cf1728.png)

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/194747585-536d7a8e-a35d-4ed5-9cba-1531243d1517.png)
