### ISSUE TITLE
Fiche adhérent

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#6]
Comment compléter la fiche adhérents avec son niveau (Petit loup, => Lynx) ainsi que les niveaux d'encadrement ( Animateur club,  Initiateur, Moniteur, Adulte expérimenté)
Devons nous préciser le lieu de naissance ?
![fiche adhérent](https://user-images.githubusercontent.com/87672341/126746780-6bc96384-e0c4-4fd3-b86a-61449280cddc.png)

@Pierre

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/126905063-c90719b6-6e43-4fb9-ac7b-84743d4f76bb.png)
