### ISSUE TITLE
liste les adhérents non renouvelés ou en cours

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#83]
Premier ticket 2022!

Pouvoir exporter ou afficher les non renouvelée ou en attente.
A ce jour seuls les "valide" sont affichés

![tri non renouvele](https://user-images.githubusercontent.com/87672341/147965154-b224be28-f3ff-44f2-9044-61fca9be4c29.png)

**Comment by pasojucle** [comment]
![Capture d’écran du 2022-03-27 19-28-49](https://user-images.githubusercontent.com/54477272/160293264-2392f392-0afb-4671-8df4-d94a01d283a7.png)

**Comment by VTTPierre** [comment]
Dans les adhérents, supprimer 3 séances en cours et terminées
Inscription ajouter les 3 séances terminées

**Comment by VTTPierre** [comment]
Bonjour Patrick. 
Est il possible de paramétrer la largeur du bandeau lors de l'envoi d'un mail depuis le site. 
Voir PJ 
Le bandeau occupe tout l'espace et le texte est hyper petit. Tout ceci en consultation depuis le mobile. 
Bonne journée et bon week-end 
 
Envoyé depuis l'application Mail Orange
----------------Le 08/04/2022, à 12:54, pasojucle a écrit :
Closed #83.
