### ISSUE TITLE
Système d'indemnité

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#96]

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/163849111-279551dd-c680-4790-8309-3c9895126e62.png)

**Comment by VTTPierre** [comment]
le total n'est pas pris en compte 
![calcul des indem](https://user-images.githubusercontent.com/87672341/188727320-b0a9ff50-dec3-4f40-b32d-eb417d89a56f.png)

**Comment by pasojucle** [comment]
![image](https://user-images.githubusercontent.com/54477272/188947079-d776b619-c9b6-4b97-9b53-9d9c411f1be4.png)
